version: '3.8'

services:
  php-fpm:
    build:
      dockerfile: Dockerfile
      context: ./docker/php-fpm
      args:
        UID: '$UID'
        GID: '$GID'
        PHP_VERSION: '$PHP_VERSION'
    user: php
    restart: always
    volumes:
      - ./nats-laravel:/var/www

  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: --js --debug --trace --sd /data -p 4222 -m 8222
    volumes:
      - ./docker/nats/jetstream-cluster/n1:/data

  prometheus-nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command: "-connz -varz -channelz -serverz -subz -healthz -routez http://nats:8222"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./docker/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD='$GRAFANA_PASSWORD'
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=5s
    links:
      - prometheus

  caddy:
    image: caddy:alpine
    depends_on:
      - php-fpm
    restart: always
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./nats-laravel:/var/www/
    ports:
      - '80:80'
